### PR TITLE
Add additional input parameter information

### PR DESCRIPTION
**Pull request by amandadumi**
This pull request is meant to serve as a place to discuss the best way to incorporate the additional parameters as requested https://github.com/cclib/cclib/pull/1143, and discussed within cclib https://github.com/cclib/cclib/pull/1148.

A list of the added variables to inputParameters is:
- grid
- dispersion
- memory
- processors
- keywords_line
- run_date (should maybe be placed elsewhere as discussed in 1143)

This is marked as draft since this will depend on some of the clarifications I requested in 1148 in term of what data expected. Though, if there is any feedback as of now, I am happy to start making edits.

### CODE REVIEW

**Comment by ghutchis** [comment]
I think date / timing would be better served elsewhere, like a `metadata` key. It's not an input parameter.

I could go for `keywords` (not `keywords_list`) but I think the question is whether it's a redundant list (e.g., including grid, basis, etc.) or "the other keywords not indicated."

**Comment by amandadumi** [comment]
I've added a metadata section and switched to camel casing. 

In regards to 1143 pull request mentioned above, some descriptions have been updated. Keyword_list will still need some decisions to be made on a final form. If this were implemented naively, there could be some redundant data but could be value when keywords are included that aren't actually parsed into metadata, but could be important for reproducibility. If this should be added later once we have a more clear structure, I understand and remove it from this pull request and introduce it later.

**Comment by amandadumi** [comment]
After talking about with the cclib team, we will spend some time thinking about what should/should not be in keywords and how to approach parsing that. In the meantime, I've removed the keywords object from inputParameters for now and will open a later pull request for it when ready. Let me know what you think!

**Comment by amandadumi** [comment]
Hello, I just wanted to check in to see if there was anything I could do to help move this forward?

**Review by cryos — APPROVED** [review]
This looks good to me, I removed some trailing whitespace.

**Pull request merged**
